### ISSUE TITLE
Tested at University of Granada (Spain)

### ISSUE THREAD

**Issue by kcobos** [martinius96/ESP32-Eduroam#1]
Tested at Universidad de Granada (Spain) under Lolin D32 Pro (https://wiki.wemos.cc/products:d32:d32_pro) and Lolin D32 (https://wiki.wemos.cc/products:d32:d32) boards. It works perfectly.

**Comment by martinius96** [comment]
Thanks a lot, I will add it to verified locations!

**Comment by martinius96** [comment]
@kcobos Can you please test one experimental sketch? I am not now at unversity to test it, if you are able to, i can send it to your mail... Thanks, Martin

**Comment by kcobos** [comment]
Sure, send it to me info@kcobos.es. I have two boards to test it.
