### ISSUE TITLE
Tested at University of Regensburg (Germany)

### ISSUE THREAD

**Issue by Lyniat** [martinius96/ESP32-Eduroam#2]
Tested at University of Regensburg (Germany)
Lolin32 works without any problems.

**Comment by martinius96** [comment]
Hello there, thanks for reply. I will upload table of working places. Can i ask which sketch have u using? 

I added experimental sketch to repository but i haven't time to test it. Thanks, Martin :)

**Comment by Lyniat** [comment]
I tested new_fix

**Comment by martinius96** [comment]
Thanks :)
